services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: pokecache
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pokecli-api:0.1-foundation
    container_name: pokecli-api-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: pokecache
      PORT: 8080
    depends_on:
      - mongo

volumes:
  mongo_data: